# This workflow runs when a push to main is done, when a pull request targeting main is opened or updated, or when the workflow is manually triggered
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (git tag)'
        required: true
        type: string

  workflow_call:
    inputs:
      version:
        description: 'Version to build (git tag)'
        required: true
        type: string

name: Build and Package

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.version || github.ref }}

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Clean npm cache and remove existing dependencies
        run: |
          rm -f package-lock.json
          rm -rf node_modules

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build --if-present

      - name: Copy package.json and package-lock.json
        run: |
          cp package.json package-lock.json dist/
          ls -la dist/

      - name: Generate safe artifact name
        id: artifact-name
        run: |
          NAME="${{ inputs.version || github.ref_name || github.sha }}"
          echo "safe_name=${NAME//\//-}" >> $GITHUB_OUTPUT

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact-${{ steps.artifact-name.outputs.safe_name }}
          path: dist/*
